#!/usr/bin/env python

import os, subprocess, datetime, tempfile

#cmd = "./mergePlot --data-mjb ../analysis/output_rootfile/11Jan15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root --mc-mjb ../analysis/output_rootfile/11Jan15/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix.root  --data-mpf ../analysis/output_rootfile/11Jan15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root --mc-mpf ../analysis/output_rootfile/11Jan15/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lin --plotName \"_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_afterPrescaleReweighting_withSystErrors_QCD-HT\" --extension \".pdf\"  --useSyst --syst-file-mjb \"../compareMC/output_rootfile/compareMC_woPU_pt30_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix.root \" --syst-file-mpf \"../compareMC/output_rootfile/compareMC_woPU_pt10_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix.root \" "
#cmd = "./mergePlot --data-mjb ../analysis/output_rootfile/21May15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting.root --mc-mjb ../analysis/output_rootfile/11Jan15/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix.root  --data-mpf ../analysis/output_rootfile/21May15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting.root --mc-mpf ../analysis/output_rootfile/11Jan15/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lin --plotName \"_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_afterPrescaleReweighting_withSystErrors_QCD-HT_closure\" --extension \".pdf\"  --useSyst --syst-file-mjb \"../compareMC/output_rootfile/compareMC_woPU_pt30_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix.root \" --syst-file-mpf \"../compareMC/output_rootfile/compareMC_woPU_pt10_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix.root \" "

# Add JES uncertainties obtained after closure, using Winter14_V8_MC_Uncertainty_AK5PFchs.txt
#cmd = "./mergePlot --data-mjb ../analysis/output_rootfile/21May15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting.root --mc-mjb ../analysis/output_rootfile/11Jan15/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix.root  --data-mpf ../analysis/output_rootfile/21May15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting.root --mc-mpf ../analysis/output_rootfile/11Jan15/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lin --plotName \"_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_afterPrescaleReweighting_withSystErrors_QCD-HT_closure\" --extension \".pdf\"  --useSyst --syst-file-mjb \"../compareMC/output_rootfile/compareMC_woPU_pt30_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix_29Jun16.root \" --syst-file-mpf \"../compareMC/output_rootfile/compareMC_woPU_pt10_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix_29Jun16.root \" "

# Try other MC
# Using pythia
#cmd = "./mergePlot --data-mjb ../analysis/output_rootfile/11Jan15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root --mc-mjb ../analysis/output_rootfile/23May16/MC/MULTIJET_MC_QCD-Pt-pythia-120To1400_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix.root  --data-mpf ../analysis/output_rootfile/11Jan15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root --mc-mpf ../analysis/output_rootfile/23May16/MC/MULTIJET_MC_QCD-Pt-pythia-120To1400_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lin --plotName \"_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_afterPrescaleReweighting_withSystErrors_Pythia\" --extension \".pdf\"  --useSyst --syst-file-mjb \"../compareMC/output_rootfile/compareMC_woPU_pt30_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix.root \" --syst-file-mpf \"../compareMC/output_rootfile/compareMC_woPU_pt10_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix.root \" "

# Using Herwig
cmd = "./mergePlot --data-mjb ../analysis/output_rootfile/11Jan15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root --mc-mjb ../analysis/output_rootfile/23May16/MC/MULTIJET_MC_QCD-Pt-herwig-120ToInf_analysis_woPU_pt30_eta50_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix.root  --data-mpf ../analysis/output_rootfile/11Jan15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root --mc-mpf ../analysis/output_rootfile/23May16/MC/MULTIJET_MC_QCD-Pt-herwig-120ToInf_analysis_woPU_pt10_eta50_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix.root --lin --plotName \"_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_afterPrescaleReweighting_withSystErrors_Herwig\" --extension \".pdf\"  --useSyst --syst-file-mjb \"../compareMC/output_rootfile/compareMC_woPU_pt30_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix.root \" --syst-file-mpf \"../compareMC/output_rootfile/compareMC_woPU_pt10_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix.root \" "

os.system(cmd);

