#!/usr/bin/env python

import os, subprocess, datetime, tempfile
# last 8 TeV results
#11Jan15
#21May15 -> closure
# WARNING! in this case, name of vLeadingJetPt_RefObjPtHLT_data_lumi is different ("leadingJet/HLTPtBin/LeadingJetPt_" + ptBinName; instead of "leadingJet/HLTPtBin/LeadingJetPt_perHLTTrigger_" + ptBinName)


#cmd = "./dataMcComparison ../analysis/output_rootfile/11Jan15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root ../analysis/output_rootfile/11Jan15/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting_QCD-HT\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/11Jan15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root ../analysis/output_rootfile/11Jan15/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting_QCD-HT\" --extension \".pdf\""

#cmd = "./dataMcComparison ../analysis/output_rootfile/21May15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting.root ../analysis/output_rootfile/11Jan15/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --plotName \"_pt10_eta50_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting_withSystErrors_QCD-HT\" --extension \".pdf\"  --recoilPtBin --recoilPtHLTBin "
#cmd = "./dataMcComparison ../analysis/output_rootfile/21May15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting.root ../analysis/output_rootfile/11Jan15/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --plotName \"_pt30_eta50_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting_withSystErrors_QCD-HT\" --extension \".pdf\"  --recoilPtBin --recoilPtHLTBin"


#01May16 -> same 8 TeV but relaunched with new response per pt bin binning

cmd = "./dataMcComparison ../analysis/output_rootfile/01May16/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_beforePrescaleReweighting.root ../analysis/output_rootfile/01May16/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_beforePrescaleReweighting_QCD-HT\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/01May16/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_beforePrescaleReweighting.root ../analysis/output_rootfile/01May16/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_beforePrescaleReweighting_QCD-HT\" --extension \".pdf\""

#cmd = "./dataMcComparison ../analysis/output_rootfile/01May16/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root ../analysis/output_rootfile/01May16/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting_QCD-HT\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/01May16/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root ../analysis/output_rootfile/01May16/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting_QCD-HT\" --extension \".pdf\""

#cmd = "./dataMcComparison ../analysis/output_rootfile/01May16/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting.root ../analysis/output_rootfile/01May16/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --plotName \"_pt10_eta50_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting_QCD-HT\" --extension \".pdf\"  --recoilPtBin --recoilPtHLTBin "
#cmd = "./dataMcComparison ../analysis/output_rootfile/01May16/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting.root ../analysis/output_rootfile/01May16/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --plotName \"_pt30_eta50_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting_QCD-HT\" --extension \".pdf\"  --recoilPtBin --recoilPtHLTBin"

# 21May16 : relaunch 01May16 but removing 1st pt recoil bin 210-250 (ie cut on pt recoil at 250)
#cmd = "./dataMcComparison ../analysis/output_rootfile/21May16/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root ../analysis/output_rootfile/21May16/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting_QCD-HT\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/21May16/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root ../analysis/output_rootfile/21May16/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting_QCD-HT\" --extension \".pdf\""

# 23May16 : relaunch 01May16 for recoil with pt>20
#cmd = "./dataMcComparison ../analysis/output_rootfile/23May16/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt20_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root ../analysis/output_rootfile/23May16/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt20_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt20_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting_QCD-HT\" --extension \".pdf\""

# 13 TeV
#cmd = "./dataMcComparison ../analysis/output_rootfile/23Jul15/data/MULTIJET_data_JetHT_Run2015B-PromptReco_miniAOD_woPU_pt30_eta50_notRmPUJets_beforePrescaleReweighting.root ../analysis/output_rootfile/21Jul15/MC/MULTIJET_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_bx50_miniAOD_woPU_pt30_eta50_notRmPUJets.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt30_eta50_notRmPUJets_recoilPtHLTBin_type1fix_beforePrescaleReweighting_QCD-HT_13TeV_50ns\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/30Jul15/data/MULTIJET_data_JetHT_Run2015B-PromptReco_miniAOD_woPU_pt10_eta50_notRmPUJets_beforePrescaleReweighting.root ../analysis/output_rootfile/30Jul15/MC/MULTIJET_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_bx50_miniAOD_woPU_pt10_eta50_notRmPUJets.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt10_eta50_notRmPUJets_recoilPtHLTBin_type1fix_beforePrescaleReweighting_QCD-HT_13TeV_50ns\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/25Aug15/data/MULTIJET_data_JetHT_Run2015B-PromptReco_miniAOD_woPU_pt30_eta50_notRmPUJets_beforePrescaleReweighting.root ../analysis/output_rootfile/25Aug15/MC/MULTIJET_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_bx50_miniAOD_woPU_pt30_eta50_notRmPUJets.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt30_eta50_notRmPUJets_recoilPtHLTBin_type1fix_beforePrescaleReweighting_QCD-HT_13TeV_50ns\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/18Sep15/data/MULTIJET_data_JetHT_Run2015C-PromptReco_miniAOD_woPU_pt10_eta50_notRmPUJets_beforePrescaleReweighting.root ../analysis/output_rootfile/18Sep15/MC/MULTIJET_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_bx25_miniAOD_woPU_pt10_eta50_notRmPUJets.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt10_eta50_notRmPUJets_recoilPtHLTBin_type1fix_beforePrescaleReweighting_QCD-HT_13TeV_25ns\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/28Sep15/data/MULTIJET_data_JetHT_Run2015C-PromptReco_miniAOD_woPU_pt10_eta50_notRmPUJets_beforePrescaleReweighting.root ../analysis/output_rootfile/28Sep15/MC/MULTIJET_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_bx25_miniAOD_woPU_pt10_eta50_notRmPUJets.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt10_eta50_notRmPUJets_recoilPtHLTBin_type1fix_beforePrescaleReweighting_QCD-HT_13TeV_25ns\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/29Sep15/data/MULTIJET_data_JetHT_Run2015D-PromptReco_miniAOD_woPU_pt10_eta50_notRmPUJets_beforePrescaleReweighting.root ../analysis/output_rootfile/29Sep15/MC/MULTIJET_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_bx25_miniAOD_woPU_pt10_eta50_notRmPUJets.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt10_eta50_notRmPUJets_recoilPtHLTBin_type1fix_beforePrescaleReweighting_QCD-HT_13TeV_25ns\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/07Oct15/data/MULTIJET_data_JetHT_Run2015D-PromptReco_miniAOD_woPU_pt30_eta50_notRmPUJets_beforePrescaleReweighting_closure.root ../analysis/output_rootfile/07Oct15/MC/MULTIJET_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_bx25_miniAOD_woPU_pt30_eta50_notRmPUJets.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt30_eta50_notRmPUJets_recoilPtHLTBin_type1fix_beforePrescaleReweighting_QCD-HT_13TeV_25ns_closure\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/07Oct15/data/MULTIJET_data_JetHT_Run2015D-PromptReco_miniAOD_woPU_pt30_eta50_notRmPUJets_beforePrescaleReweighting_onlyL2Res.root ../analysis/output_rootfile/07Oct15/MC/MULTIJET_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_bx25_miniAOD_woPU_pt30_eta50_notRmPUJets.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt30_eta50_notRmPUJets_recoilPtHLTBin_type1fix_beforePrescaleReweighting_QCD-HT_13TeV_25ns_onlyL2Res\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/17Oct15/data/MULTIJET_data_JetHT_Run2015D-PromptReco_miniAOD_woPU_pt10_eta50_notRmPUJets_beforePrescaleReweighting_onlyL2Res.root ../analysis/output_rootfile/17Oct15/MC/MULTIJET_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_bx25_miniAOD_woPU_pt10_eta50_notRmPUJets.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt10_eta50_notRmPUJets_recoilPtHLTBin_type1fix_beforePrescaleReweighting_QCD-HT_13TeV_25ns_onlyL2Res\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/26Oct15/data/MULTIJET_data_JetHT_Run2015D-PromptReco_miniAOD_woPU_pt30_eta50_notRmPUJets_beforePrescaleReweighting_onlyL2Res.root ../analysis/output_rootfile/26Oct15/MC/MULTIJET_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_bx25_miniAOD_woPU_pt30_eta50_notRmPUJets.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt30_eta50_notRmPUJets_recoilPtHLTBin_type1fix_beforePrescaleReweighting_QCD-HT_13TeV_25ns_onlyL2Res\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/17Oct15/data/MULTIJET_data_JetHT_Run2015D-PromptReco_miniAOD_woPU_pt10_eta50_notRmPUJets_beforePrescaleReweighting_onlyL2Res_DCSOnly.root ../analysis/output_rootfile/17Oct15/MC/MULTIJET_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_bx25_miniAOD_woPU_pt10_eta50_notRmPUJets.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt10_eta50_notRmPUJets_recoilPtHLTBin_type1fix_beforePrescaleReweighting_QCD-HT_13TeV_25ns_onlyL2Res_DCSOnly\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/28Oct15/data/MULTIJET_data_JetHT_Run2015D-merged_miniAOD_woPU_pt30_eta50_notRmPUJets_beforePrescaleReweighting_json19Oct15.root ../analysis/output_rootfile/28Oct15/MC/MULTIJET_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_bx25_miniAOD_woPU_pt30_eta50_notRmPUJets.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt30_eta50_notRmPUJets_recoilPtHLTBin_type1fix_beforePrescaleReweighting_QCD-Pt_13TeV_25ns\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/30Oct15/data/MULTIJET_data_JetHT_Run2015D-merged_miniAOD_woPU_pt10_eta50_notRmPUJets_beforePrescaleReweighting_json19Oct15.root ../analysis/output_rootfile/30Oct15/MC/MULTIJET_QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_bx25_miniAOD_woPU_pt10_eta50_notRmPUJets.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt10_eta50_notRmPUJets_recoilPtHLTBin_type1fix_beforePrescaleReweighting_QCD-Pt_13TeV_25ns\" --extension \".pdf\""
#cmd = "./dataMcComparison ../analysis/output_rootfile/23Dec15/data/MULTIJET_data_JetHT_Run2015D-merged_miniAOD_woPU_pt30_eta50_notRmPUJets_beforePrescaleReweighting_json13Nov15.root ../analysis/output_rootfile/23Dec15/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt30_eta50_notRmPUJets_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --recoilPtBin --recoilPtHLTBin --plotName \"_pt30_eta50_notRmPUJets_recoilPtHLTBin_type1fix_beforePrescaleReweighting_QCD-HT_13TeV_25ns\" --extension \".pdf\""


os.system(cmd);

