#!/usr/bin/env python

import os, subprocess, datetime, tempfile
# last 8 TeV results
#11Jan15
#21May15 -> closure
# WARNING! in this case, name of vLeadingJetPt_RefObjPtHLT_data_lumi is different ("leadingJet/HLTPtBin/LeadingJetPt_" + ptBinName; instead of "leadingJet/HLTPtBin/LeadingJetPt_perHLTTrigger_" + ptBinName)

#cmd = "./dataMcComparison ../analysis/output_rootfile/21May15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting.root ../analysis/output_rootfile/11Jan15/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --plotName \"_pt10_eta50_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting_withSystErrors_QCD-HT\" --extension \".pdf\"  --recoilPtBin --recoilPtHLTBin --useSyst --syst-file \"../compareMC/output_rootfile/compareMC_woPU_pt10_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix.root \" "
#cmd = "./dataMcComparison ../analysis/output_rootfile/21May15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting.root ../analysis/output_rootfile/11Jan15/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --plotName \"_pt30_eta50_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting_withSystErrors_QCD-HT\" --extension \".pdf\"  --recoilPtBin --recoilPtHLTBin --useSyst --syst-file \"../compareMC/output_rootfile/compareMC_woPU_pt30_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix.root \" "

#cmd = "./dataMcComparison ../analysis/output_rootfile/11Jan15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root ../analysis/output_rootfile/11Jan15/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --plotName \"_pt10_eta50_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_afterPrescaleReweighting_withSystErrors_QCD-HT\" --extension \".pdf\"  --recoilPtBin --recoilPtHLTBin --useSyst --syst-file \"../compareMC/output_rootfile/compareMC_woPU_pt10_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix.root \" "
#cmd = "./dataMcComparison ../analysis/output_rootfile/11Jan15/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root ../analysis/output_rootfile/11Jan15/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --plotName \"_pt30_eta50_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_afterPrescaleReweighting_withSystErrors_QCD-HT\" --extension \".pdf\"  --recoilPtBin --recoilPtHLTBin --useSyst --syst-file \"../compareMC/output_rootfile/compareMC_woPU_pt30_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix.root \" "


#01May16 -> same 8 TeV but relaunched with new response per pt bin binning

#cmd = "./dataMcComparison ../analysis/output_rootfile/01May16/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting.root ../analysis/output_rootfile/01May16/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --plotName \"_pt10_eta50_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting_withSystErrors_QCD-HT\" --extension \".pdf\"  --recoilPtBin --recoilPtHLTBin --useSyst --syst-file \"../compareMC/output_rootfile/compareMC_woPU_pt10_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix.root \" "
#cmd = "./dataMcComparison ../analysis/output_rootfile/01May16/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting.root ../analysis/output_rootfile/01May16/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --plotName \"_pt30_eta50_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting_withSystErrors_QCD-HT\" --extension \".pdf\"  --recoilPtBin --recoilPtHLTBin --useSyst --syst-file \"../compareMC/output_rootfile/compareMC_woPU_pt30_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix.root \" "

# Add JES uncertainties obtained after closure, using Winter14_V8_MC_Uncertainty_AK5PFchs.txt

#cmd = "./dataMcComparison ../analysis/output_rootfile/01May16/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting.root ../analysis/output_rootfile/01May16/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --plotName \"_pt10_eta50_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting_withSystErrors_QCD-HT\" --extension \".pdf\"  --recoilPtBin --recoilPtHLTBin --useSyst --syst-file \"../compareMC/output_rootfile/compareMC_woPU_pt10_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix_29Jun16.root \" "
cmd = "./dataMcComparison ../analysis/output_rootfile/01May16/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting.root ../analysis/output_rootfile/01May16/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --plotName \"_pt30_eta50_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_closure_afterPrescaleReweighting_withSystErrors_QCD-HT\" --extension \".pdf\"  --recoilPtBin --recoilPtHLTBin --useSyst --syst-file \"../compareMC/output_rootfile/compareMC_woPU_pt30_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix_29Jun16.root \" "

#cmd = "./dataMcComparison ../analysis/output_rootfile/01May16/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root ../analysis/output_rootfile/01May16/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt10_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --plotName \"_pt10_eta50_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_afterPrescaleReweighting_withSystErrors_QCD-HT\" --extension \".pdf\"  --recoilPtBin --recoilPtHLTBin --useSyst --syst-file \"../compareMC/output_rootfile/compareMC_woPU_pt10_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix.root \" "
#cmd = "./dataMcComparison ../analysis/output_rootfile/01May16/data/MULTIJET_Run2012ABCD-22Jan2013_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix_afterPrescaleReweighting.root ../analysis/output_rootfile/01May16/MC/MULTIJET_MC_QCD-HT-100ToInf_analysis_woPU_pt30_eta50_puJetIdT_recoilPtHLTBin_type1fix.root --lumi --shape --lin --rmPU --plotName \"_pt30_eta50_puJetIdT_HLTsel_woPtRecoilCut_recoilPtHLTBin_type1fix_afterPrescaleReweighting_withSystErrors_QCD-HT\" --extension \".pdf\"  --recoilPtBin --recoilPtHLTBin --useSyst --syst-file \"../compareMC/output_rootfile/compareMC_woPU_pt30_eta50_puJetIdT_woPtRecoilCut_recoilPtHLTBin_type1fix.root \" "



os.system(cmd);

